In [ ]:
# Here we will see how to create and work with multidimensional arrays using NumPy and perform slicing operations.

In [ ]:
import numpy as np

array = np.array([[1,2 ,3 ,4 ],                      # Creating a 2D array
                  [5,6 ,7 ,8 ],
                  [9,10,11,12],
                  [13,14,15,16]])

print("Original Array:\n", array)                    # Displaying the original array
print("Array Dimension:", array.ndim)                # Displaying the number of dimensions
print("Array Shape:", array.shape)                   # Displaying the shape of the array

Original Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Array Dimension: 2
Array Shape: (4, 4)


In [ ]:
# For performing slicing operations on the array
# [start:stop:step] - Slicing syntax

In [ ]:
# For accessing Array rows using slicing
print(f"First row:  {array[0]}")                    # Accessing the first row
print(f"Second row: {array[1]}")                    # Accessing the second row
print(f"Third row:  {array[2]}")                    # Accessing the third row
print(f"Fourth row: {array[3]}")                    # Accessing the fourth row

First row:  [1 2 3 4]
Second row: [5 6 7 8]
Third row:  [ 9 10 11 12]
Fourth row: [13 14 15 16]


In [ ]:
# For accessing Array rows in range using slicing

print(f"Rows from index 0 to 2:\n{array[0:3]}\n")       # Accessing rows from index 0 to 2
print(f"Rows from index 0 to 3:\n{array[0:4]}\n")       # Accessing rows from index 0 to 3
print(f"Rows from index 1 to 2:\n{array[1:3]}\n")       # Accessing rows from index 1 to 2
print(f"Rows only 1:\n{array[1:2]}\n")                  # Accessing rows only 1

Rows from index 0 to 2:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Rows from index 0 to 3:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Rows from index 1 to 2:
[[ 5  6  7  8]
 [ 9 10 11 12]]

Rows only 1:
[[5 6 7 8]]



In [14]:
# For accessing Array rows with step using slicing

print(f"Rows from index 0 to 4 with step 2:\n{array[0::2]}\n")  # Accessing rows from index 0 to 4 with step 2

Rows from index 0 to 4 with step 2:
[[ 1  2  3  4]
 [ 9 10 11 12]]



In [15]:
# For accessing Array rows in reverse order using slicing

print(f"Last row:        {array[-1]}")               # Accessing the last row
print(f"Second last row: {array[-2]}")               # Accessing the second last row
print(f"Third last row:  {array[-3]}")               # Accessing the third last row
print(f"Fourth last row: {array[-4]}")               # Accessing the fourth last row

Last row:        [13 14 15 16]
Second last row: [ 9 10 11 12]
Third last row:  [5 6 7 8]
Fourth last row: [1 2 3 4]


In [16]:
# For accessing Original Array in reverse order using slicing

print(f"Array in reverse order:\n{array[::-1]}\n")   # Accessing the array in reverse order

Array in reverse order:
[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]



In [17]:
# For accessing Original Array in reverse order with step using slicing

print(f"Array in reverse order with step 2:\n{array[::-2]}\n")  # Accessing the array in reverse order with step 2

Array in reverse order with step 2:
[[13 14 15 16]
 [ 5  6  7  8]]



In [ ]:
# For accessing Array columns using slicing
print(f"First column:  {array[:, 0]}")              # Accessing the first column
print(f"Second column: {array[:, 1]}")              # Accessing the second column
print(f"Third column:  {array[:, 2]}")              # Accessing the third column
print(f"Fourth column: {array[:, 3]}")              # Accessing the fourth column

First column:  [ 1  5  9 13]
Second column: [ 2  6 10 14]
Third column:  [ 3  7 11 15]
Fourth column: [ 4  8 12 16]


In [18]:
# For accessing Array first 3 columns using slicing

print(f"First 3 columns:\n{array[:, :3]}")         # Accessing the first 3 columns

First 3 columns:
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


In [19]:
# For accessing Array coulumn from index 1 to 3 using slicing
print(f"Column from index 1 to 3:\n{array[:, 1:4]}")         # Accessing the column from index 1 to 3

Column from index 1 to 3:
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]


In [22]:
# For accessing Array columns from index 0 to 4 with step 2 using slicing

print(f"Columns from index 1 to 4 with step 2:\n{array[:,1::2]}")  # Accessing columns from index 1 to 4 with step 2

Columns from index 1 to 4 with step 2:
[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]]


In [23]:
# For accessing Array columns in reverse order using slicing

print(f"Columns in reverse order:\n{array[:,::-1]}")   # Accessing columns in reverse order

Columns in reverse order:
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


In [24]:
# For accessing Array columns in reverse order using slicing with step 2

print(f"Columns in reverse order with step 2: \n {array[:,::-2]}")  # Accessing columns in reverse order with step 2

Columns in reverse order with step 2: 
 [[ 4  2]
 [ 8  6]
 [12 10]
 [16 14]]


In [25]:
# For accessing first 2 rows and first 2 columns using slicing

print(f"First 2 rows and first 2 columns:\n{array[0:2, 0:2]}")   # Accessing first 2 rows and first 2 columns

# For accessing last 2 rows and first 2 columns using slicing

print(f"last 2 rows and first 2 columns:\n{array[2:4, 0:2]}")     # Accessing last 2 rows and first 2 columns

# For accessing first 2 rows and last 2 columns using slicing   

print(f"First 2 rows and last 2 columns:\n{array[0:2, 2:4]}")     # Accessing first 2 rows and last 2 columns

# For accessing last 2 rows and last 2 columns using slicing

print(f"Last 2 rows and last 2 columns:\n{array[2:4, 2:4]}")     # Accessing last 2 rows and last 2 columns     

First 2 rows and first 2 columns:
[[1 2]
 [5 6]]
last 2 rows and first 2 columns:
[[ 9 10]
 [13 14]]
First 2 rows and last 2 columns:
[[3 4]
 [7 8]]
Last 2 rows and last 2 columns:
[[11 12]
 [15 16]]
