In [ ]:
# Broadcasting allows NumPy to perform operations on an arrays with different shapes by virtually
# expanding dimensions of the lower size array.

# Either the diminsions have same size or one of the dimension has a size of 1.

# To boradCast the two arrays together either in row or column both the number should be matched
# or one of the number contain 1.

In [ ]:
# Example

import numpy as np

array1 = np.array([[1,2,3,4,5]])
array2 = np.array([[6],[7],[8],[9],[10]])


print(f"The 2D array with 1 row and 5 column:\n{array1}")                   # 1x5 array
print(f"The 2D array with 5 rows and 1 column each:\n{array2}")             # 5x1 array

# Performing BoradCasting

print(f"BroadCast Array is: \n{array1 * array2}")               # Resultant 5x5 array   



The 2D array with 1 row and 5 column:
[[1 2 3 4 5]]
The 2D array with 5 rows and 1 column each:
[[ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
BroadCast Array is: 
[[ 6 12 18 24 30]
 [ 7 14 21 28 35]
 [ 8 16 24 32 40]
 [ 9 18 27 36 45]
 [10 20 30 40 50]]
