In [ ]:
# Refers to the process of selecting elements from an array based on specific conditions or criteria.

In [6]:
from itertools import tee
import numpy as np

# Create a NumPy array
data = np.array([10, 15, 20, 25, 30, 35, 40,86,62,60])
print("Original Array:", data)

# teenagers 
print("Teenagers (age < 18):")
teenagers = data[data < 18]
print(teenagers)

# adults
print("Adults (age >= 18):")
adults = data[data >= 18]
print(adults)

# elders 
print("Elders (age >= 60):")
elders = data[data >= 60]
print(elders)

# even 
print("Even Numbers:")
even = data[data % 2 == 0]
print(even)

# odd
print("Odd Numbers:")
odd = data[data % 2 != 0]
print(odd)

Original Array: [10 15 20 25 30 35 40 86 62 60]
Teenagers (age < 18):
[10 15]
Adults (age >= 18):
[20 25 30 35 40 86 62 60]
Elders (age >= 60):
[86 62 60]
Even Numbers:
[10 20 30 40 86 62 60]
Odd Numbers:
[15 25 35]
