In [1]:
# Question 3 : # Here we will see how to calculate column-wise and row-wise statistic
# of a 2D array.

In [14]:
from netrc import NetrcParseError
import numpy as np

array = np.random.randint(1, 100, size=10)
print(f"The 1st array is : \n {array}")
array = array.reshape(2,5)
print(f"The reshaped 2D array is : \n {array}")
print("\n")

# Performing Statistics operations Column-wise
mean_col = array.mean(axis=0)
median_col = np.median(array, axis=0)
std_col = array.std(axis=0)
print(f"Mean Column-wise : {mean_col}")
print(f"Median Column-wise : {median_col}")
print(f"Standard Deviation Column-wise : {std_col}")
print("\n")

# Performing Statistics operations Row-wise
mean_row = array.mean(axis=1)
median_row = np.median(array, axis=1)
std_row = array.std(axis=1)
print(f"Mean Row-wise : {mean_row}")
print(f"Median Row-wise : {median_row}")
print(f"Standard Deviation Row-wise : {std_row}")

The 1st array is : 
 [ 7 70 98 50 88 74 45 78  8 68]
The reshaped 2D array is : 
 [[ 7 70 98 50 88]
 [74 45 78  8 68]]


Mean Column-wise : [40.5 57.5 88.  29.  78. ]
Median Column-wise : [40.5 57.5 88.  29.  78. ]
Standard Deviation Column-wise : [33.5 12.5 10.  21.  10. ]


Mean Row-wise : [62.6 54.6]
Median Row-wise : [70. 68.]
Standard Deviation Row-wise : [32.25895225 25.95072253]
