In [ ]:
# Question 6: Create a 3x3 array having values from 10-90 (in the interval of 10) and 
# store that in array1 Perform the following operations on them:
# 1. Extract the 1st row from the array
# 2. Extract the last element from the array

In [7]:
import numpy as np

# Create a sample array

array1 = np.arange(10,100,10).reshape(3,3)
print(f"Original Array:\n{array1}\n")

# Extracting the 1st row from the 3x3 matrix

row_1 = array1[0]
print(f"The first row of the 3x3 Matrix is : \n{row_1}")

# Extracting the last element from the 3x3 matrix

last_element = row_1[-1]
print(f"The last element of the first row is : \n{last_element}")

Original Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

The first row of the 3x3 Matrix is : 
[10 20 30]
The last element of the first row is : 
30
