In [ ]:
# Here we will see the use of Random functions in Numpy

In [ ]:
# Random Numbers with Integer Values

import numpy as np

# Create a NumPy array or random integers between 0 and 10

random_intergers = np.random.randint(0,11,size = 10)
print(f"Random Integers: \n {random_intergers}")

# Create a NumPy array of random integers between 0 and 10 with shape (3,3)

rand_int = np.random.randint(0,11,size = (3,3))
print(f"Random Integers with shape (3,3):\n {rand_int}")


Random Integers: 
 [4 8 0 2 6 9 4 5 5 0]
Random Integers with shape (3,3):
 [[0 1 1]
 [6 9 9]
 [5 0 4]]


In [6]:
# Random Numbers with Float Values

import numpy as np

# Create a NumPy array of random float values between 0 and 1

rand_float = np.random.rand(5)
print(f"Random Float Values: \n {rand_float}")

# Create a NumPy array of random float values with shape (2,4)
rand_float1 = np.random.uniform(0,1,size = (2,4))
print(f"Random Float Values with shape (2,4):\n {rand_float1}")

Random Float Values: 
 [0.85705748 0.89298941 0.8985722  0.31342029 0.27284047]
Random Float Values with shape (2,4):
 [[0.67284612 0.51144854 0.76159595 0.16286559]
 [0.8576616  0.50017189 0.1905415  0.0024949 ]]


In [ ]:
import numpy as np

# Create a NumPy array of random integers between 1 and 100

rand1 = np.random.rand(10) 
# here rand will generate the number of values according to the given size between 0 and 1.
print(f"The Value of random float with rand is : \n{rand1}")

rand2 = np.random.uniform(1,10,10)
# here uniform will generate the number of values according to the size in between the given range. 
print(f"The Value of random float with uniform is : \n{rand2}")

The Value of random float with rand is : 
[0.03590388 0.62949832 0.02547971 0.61115701 0.05749932 0.85248727
 0.13286885 0.91182346 0.41148648 0.42136766]
The Value of random float with uniform is : 
[7.91853239 8.05162366 4.22335757 4.4022966  6.16815519 4.23439769
 6.91792202 2.04455799 2.80027556 8.16783721]


In [18]:
# To Shuffle the random generated number.

import numpy as np

array = np.random.randint(1,11,5)
print(f"The array of random integers is: \n {array}")

# Shuffle

np.random.shuffle(array)
print(f"The shuffled array is : \n {array}")

The array of random integers is: 
 [ 1  7  7 10  3]
The shuffled array is : 
 [ 3  1  7  7 10]


In [40]:
# To print the choice of the fruit

import numpy as np

fruits = np.array(['apple','banana','mango','cherry','guavava'])

print(f"The fruit are :\n{fruits}")

fruit = np.random.choice(fruits)
print(f"The fruit of own choice is: \n{fruit}")


The fruit are :
['apple' 'banana' 'mango' 'cherry' 'guavava']
The fruit of own choice is: 
banana
