In [ ]:
# Question1 : Cerate a 1D and 2D NumPy array and print their shape.

In [ ]:
# Creating 1D array

import numpy as np

array = np.array([1,2,3,4,5])
print(f"The 1D NumPy Array is: \n {array}")

The 1D NumPy array is: 
 [1 2 3 4 5]


In [3]:
# Creating 2D array

import numpy as np

array = np.array([[1,2,3,4],[5,6,7,8]])
print(f"The 2D NumPy Array is: \n {array}")

The 2D NumPy Array is: 
 [[1 2 3 4]
 [5 6 7 8]]
