In [ ]:
# Question2 : Reshape a 1D NumPy Array into a 3x4 matrix.

In [1]:
import numpy as np

# Create a 1D NumPy array with 12 elements
array = np.arange(12)  # Here arange is used to create an array with values from 0 to 11

print(f"Original 1D Array:\n{array}")

# Reshaping the 1D array into a 3x4 matrix.

reshape_matrix = array.reshape(3,4)
print(f"Reshaped 3x4 Matrix is : \n {reshape_matrix}")

Original 1D Array:
[ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped 3x4 Matrix is : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
