In [1]:
# Question 4 : Horizontal and Vertical stacking of two NumPy Arrays.

In [2]:
import numpy as np

# Create a 1D NumPy array with 12 elements
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
array2 = np.array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

# Horizontal stacking
horizontal_stack = np.hstack((array, array2))
print(f"Horizontal Stack : \n {horizontal_stack}")

# Vertical stacking
Vertical_Stack = np.vstack((array,array2))
print(f"Vertical Stack : \n {Vertical_Stack}")

Horizontal Stack : 
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
Vertical Stack : 
 [[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]
